### PR TITLE
Run flake8 tests on all new code submissions

### PR DESCRIPTION
**Pull request by cclauss**
The Travis CI services is free for all open source projects like this one.  The owner of the this repo would need to go to https://travis-ci.org/profile (log in via GitHub) and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.

### CODE REVIEW

**Comment by ryu577** [comment]
Thanks for all the pull requests, cclauss. All your PRs made good sense and I approved them. I also flipped the switch on https://travis-ci.org/profile for pyray. Let me know if I need to do anything else. I'll also read up about travis and how to use it.

**Comment by cclauss** [comment]
https://github.com/ryu577/base/blob/master/numerical/python/visualization/Animation/CubeObjects.py#L878 seems to be appearing a lot in the flake8 reports.

**Comment by cclauss** [comment]
Also https://github.com/ryu577/base/blob/c47d8b908f8e94cdbbc212840b491501585ddcb9/numerical/python/visualization/Animation/Paraboloid.py#L916

**Comment by ryu577** [comment]
That was the old codebase. I refactored it and created a new repository (pyray) from it. But pyray should be self-sufficient. Might be that there is a dependency on some methods I forgot to copy over, causing it to look for them in the old codebase. I'll check first thing tomorrow morning.

**Comment by ryu577** [comment]
Hey, is there anyway I can see the flake8 reports you were referring to? Or, could you attach them here if you have them handy?

**Comment by ryu577** [comment]
I think I figured out those methods. They were pastImage from Paraboloid.py and new_vector_4d from CubeObjects.py. I added them and now everything needed should be in the repo itself. I also moved the docstrings for the methods inside them.

**Comment by cclauss** [comment]
https://travis-ci.org/ryu577/pyray  Where do __scale__ and __shift__ come from?

**Comment by ryu577** [comment]
Those were global variables earlier, but now should be passed as arguments to each method (to enable us to shift and scale the objects they are drawing independently). I added them as arguments to the two methods in your test and pushed just now. Sorry for all the bugs.

**Comment by ryu577** [comment]
BTW, I also just discovered that the general_base method in misc.py works perfectly with python2.7 but fails with python 3.6. The error is related to array indices. Going to push a fix for that shortly.

**Comment by cclauss** [comment]
I think with your __scale__ and __shift__ plus two PRs I just submitted, the flake8 tests will pass on both Py2 and Py3.

**Comment by cclauss** [comment]
1303 "style" violations but those are optional.  Either __autopep8__ or __yapf__ can clean up most of them but again, they are optional.  https://travis-ci.org/ryu577/pyray/jobs/328834387#L1773-L1800

**Comment by ryu577** [comment]
Cool, great to see the tests succeed. Thanks again for your commits and for setting them up. I see the violations in the raw logs of the tests. Will try and clean them up.

**Pull request merged**
